application: albumify
version: 1
runtime: python
api_version: 3

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /css
  static_dir: css
- url: /js
  static_dir: js

- url: .*
  script: main.py
